// Mocks generated by Mockito 5.4.6 from annotations
// in pf2e_app/test/test_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i8;

import 'package:auth0_flutter/auth0_flutter.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pf2e_app/features/adventures/services/adventure_service.dart'
    as _i2;
import 'package:pf2e_app/features/auth/services/auth_service.dart' as _i4;
import 'package:pf2e_app/features/profile/model/profile_record.dart' as _i3;
import 'package:pf2e_app/features/profile/services/profile_service.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAdventure_0 extends _i1.SmartFake implements _i2.Adventure {
  _FakeAdventure_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfileRecord_1 extends _i1.SmartFake implements _i3.ProfileRecord {
  _FakeProfileRecord_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i4.AuthService {
  @override
  _i5.Future<_i6.Credentials?> login() =>
      (super.noSuchMethod(
            Invocation.method(#login, []),
            returnValue: _i5.Future<_i6.Credentials?>.value(),
            returnValueForMissingStub: _i5.Future<_i6.Credentials?>.value(),
          )
          as _i5.Future<_i6.Credentials?>);

  @override
  _i5.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i6.Credentials?> getSession() =>
      (super.noSuchMethod(
            Invocation.method(#getSession, []),
            returnValue: _i5.Future<_i6.Credentials?>.value(),
            returnValueForMissingStub: _i5.Future<_i6.Credentials?>.value(),
          )
          as _i5.Future<_i6.Credentials?>);
}

/// A class which mocks [AdventureService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdventureService extends _i1.Mock implements _i2.AdventureService {
  @override
  _i5.Future<List<_i2.Adventure>> getAdventures() =>
      (super.noSuchMethod(
            Invocation.method(#getAdventures, []),
            returnValue: _i5.Future<List<_i2.Adventure>>.value(
              <_i2.Adventure>[],
            ),
            returnValueForMissingStub: _i5.Future<List<_i2.Adventure>>.value(
              <_i2.Adventure>[],
            ),
          )
          as _i5.Future<List<_i2.Adventure>>);

  @override
  _i5.Future<_i2.Adventure?> getAdventure(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAdventure, [id]),
            returnValue: _i5.Future<_i2.Adventure?>.value(),
            returnValueForMissingStub: _i5.Future<_i2.Adventure?>.value(),
          )
          as _i5.Future<_i2.Adventure?>);

  @override
  _i5.Future<_i2.Adventure> createAdventure(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#createAdventure, [name]),
            returnValue: _i5.Future<_i2.Adventure>.value(
              _FakeAdventure_0(
                this,
                Invocation.method(#createAdventure, [name]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.Adventure>.value(
              _FakeAdventure_0(
                this,
                Invocation.method(#createAdventure, [name]),
              ),
            ),
          )
          as _i5.Future<_i2.Adventure>);

  @override
  _i5.Future<void> deleteAdventure(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAdventure, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ProfileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileService extends _i1.Mock implements _i7.ProfileService {
  @override
  _i5.Future<_i3.ProfileRecord> getProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, [userId]),
            returnValue: _i5.Future<_i3.ProfileRecord>.value(
              _FakeProfileRecord_1(
                this,
                Invocation.method(#getProfile, [userId]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.ProfileRecord>.value(
              _FakeProfileRecord_1(
                this,
                Invocation.method(#getProfile, [userId]),
              ),
            ),
          )
          as _i5.Future<_i3.ProfileRecord>);

  @override
  _i5.Future<_i3.ProfileRecord> updateProfile(
    String? userId, {
    String? firstName,
    String? lastName,
    _i8.Uint8List? avatarBytes,
    String? avatarFileExtension,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateProfile,
              [userId],
              {
                #firstName: firstName,
                #lastName: lastName,
                #avatarBytes: avatarBytes,
                #avatarFileExtension: avatarFileExtension,
              },
            ),
            returnValue: _i5.Future<_i3.ProfileRecord>.value(
              _FakeProfileRecord_1(
                this,
                Invocation.method(
                  #updateProfile,
                  [userId],
                  {
                    #firstName: firstName,
                    #lastName: lastName,
                    #avatarBytes: avatarBytes,
                    #avatarFileExtension: avatarFileExtension,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.ProfileRecord>.value(
              _FakeProfileRecord_1(
                this,
                Invocation.method(
                  #updateProfile,
                  [userId],
                  {
                    #firstName: firstName,
                    #lastName: lastName,
                    #avatarBytes: avatarBytes,
                    #avatarFileExtension: avatarFileExtension,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i3.ProfileRecord>);
}
