name: pf2e_app
description: "A collection of tools for Pathfinder 2nd Edition."
publish_to: 'none'
version: 0.1.0-alpha+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^11.1.0
  auth0_flutter: ^2.0.0
  command_it: ^9.5.1
  flutter_dotenv: ^6.0.0
  get_it: ^9.2.1
  intl: ^0.20.2
  listen_it: ^5.3.5
  supabase_flutter: ^2.0.0
  watch_it: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^10.5.0
  build_runner: ^2.4.8
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  network_image_mock: ^2.1.1

flutter:
  default-flavor: production
  uses-material-design: true

  assets:
    # Required for flutter_dotenv to load environment variables from a file.
    - path: .env
