name: Flutter test and build

on:
  pull_request:
    branches:
      - 'main'
  push:
    tags:
      - 'v*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Create .env file
        run: |
          echo "AUTH0_DOMAIN=" > .env
          echo "AUTH0_CLIENT_ID=" >> .env
          echo "AUTH0_SCHEME=" >> .env
          echo "SUPABASE_URL=" >> .env
          echo "SUPABASE_PUBLISHABLE_KEY=" >> .env

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: stable

      - name: Setup Flutter dependencies
        run: flutter pub get

      - name: Run build runner
        run: dart run build_runner build

      - name: Run Flutter analyze
        run: flutter analyze

      - name: Run all tests
        run: flutter test --coverage

  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    needs: test

    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
      deployment: false

    env:
      BUILD_FLAVOR: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}

    steps:
      - uses: actions/checkout@v6

      - name: Create .env file
        run: |
          echo "AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}" > .env
          echo "AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}" >> .env
          echo "AUTH0_SCHEME=${{ secrets.AUTH0_SCHEME }}" >> .env
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "SUPABASE_PUBLISHABLE_KEY=${{ secrets.SUPABASE_PUBLISHABLE_KEY }}" >> .env

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: stable

      - name: Setup Flutter dependencies
        run: flutter pub get

      - name: Run build runner
        run: dart run build_runner build

      - name: Build APK
        run: flutter build apk --build-number=${{ github.run_number }} --flavor $BUILD_FLAVOR --split-per-abi

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v6
        with:
          name: build-android
          path: build/app/outputs/flutter-apk/app-*-release.apk
